version: '3'

services:
  minecraft:
    image: dangerbarber/papermc:latest
    stdin_open: true
    tty: true
    restart: always
    networks:
      - minecraft
    ports:
      - 25565:25565 # minecraft port
      - 25590:25590 # dynmap port
      - 25591:25591 # webconsole websocket port
    volumes:
      - config:/opt/minecraft/config
      - worlds:/opt/minecraft/worlds
      - plugins:/opt/minecraft/plugins
      - data:/opt/minecraft/data
      - logs:/opt/minecraft/logs
  
  mysql:
    image: mariadb:latest
    restart: always
    networks:
      - minecraft
    ports:
      - 25601:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: CHANGEME
      MYSQL_DATABASE: minecraft
      MYSQL_USER: minecraft
      MYSQL_PASSWORD: CHANGEME

volumes:
  config: {}
  worlds: {}
  plugins: {}
  data: {}
  logs: {}
  mysql_data: {}

networks:
  minecraft: {}
