version: '3'

services:
  minecraft:
    build: ./papermc/Dockerfile
    stdin_open: true
    tty: true
    depends_on:
      - mysql
    restart: always
    networks:
      - minecraft
    ports:
      - 25565:25565 # minecraft port
      - 25590:25590 # dynmap port
    volumes:
      - config:/opt/minecraft/config
      - worlds:/opt/minecraft/worlds
      - plugins:/opt/minecraft/plugins
      - data:/opt/minecraft/data
      - logs:/opt/minecraft/logs
  
  mysql:
    image: mariadb:latest
    restart: always
    networks:
      - minecraft
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

volumes:
  config: {}
  worlds: {}
  plugins: {}
  data: {}
  logs: {}
  mysql_data: {}

networks:
  minecraft: {}
